// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-G455MsIbhMbExMxTeFdgx_kaCQhF-Q',
    appId: '1:749088809233:web:7d6613224cfd673df8ecb0',
    messagingSenderId: '749088809233',
    projectId: 'flutter-finki',
    authDomain: 'flutter-finki.firebaseapp.com',
    storageBucket: 'flutter-finki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbtKxJhUcJ1ja21a_OYaA7suYaMgOi_g',
    appId: '1:749088809233:android:4de8bee2462cc429f8ecb0',
    messagingSenderId: '749088809233',
    projectId: 'flutter-finki',
    storageBucket: 'flutter-finki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCShdHbxh5RiioJE6tjeAxwmmbphi7JwKE',
    appId: '1:749088809233:ios:cee6682bf5e87339f8ecb0',
    messagingSenderId: '749088809233',
    projectId: 'flutter-finki',
    storageBucket: 'flutter-finki.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCShdHbxh5RiioJE6tjeAxwmmbphi7JwKE',
    appId: '1:749088809233:ios:24a84f52f8d83632f8ecb0',
    messagingSenderId: '749088809233',
    projectId: 'flutter-finki',
    storageBucket: 'flutter-finki.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
