// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCnmk84IsC707i89kwjQjiNfK2NXdEOw',
    appId: '1:866444548382:web:324b33492876026488110f',
    messagingSenderId: '866444548382',
    projectId: 'mis-homework-2',
    authDomain: 'mis-homework-2.firebaseapp.com',
    storageBucket: 'mis-homework-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOoFLoXP6-ijHDIIvrfmMSveirGoL594',
    appId: '1:866444548382:android:e38eff9b1968751788110f',
    messagingSenderId: '866444548382',
    projectId: 'mis-homework-2',
    storageBucket: 'mis-homework-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB_e6bk3j890pRWM3GAmuMhKX6bPLqo-Q',
    appId: '1:866444548382:ios:2840d25ad21ef63988110f',
    messagingSenderId: '866444548382',
    projectId: 'mis-homework-2',
    storageBucket: 'mis-homework-2.appspot.com',
    iosBundleId: 'com.example.dom2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB_e6bk3j890pRWM3GAmuMhKX6bPLqo-Q',
    appId: '1:866444548382:ios:93472ee22763eb2688110f',
    messagingSenderId: '866444548382',
    projectId: 'mis-homework-2',
    storageBucket: 'mis-homework-2.appspot.com',
    iosBundleId: 'com.example.dom2.RunnerTests',
  );
}
